### ISSUE TITLE
Player's price won't increase and resets after reconnecting

### ISSUE THREAD

**Issue by ZUNII** [drunkdriversclub/ddc#7]
**Describe the bug**
Every time i join DDC my price starts at 1000$, then i play for several hours and i get 40 wins ( just an example), my price goes up to 40,000$, which is completely normal since 1 win = +1000$ to the player's price. But sadly when I reconnect this value goes back to 1000$ and i have to start all over again.

**To Reproduce**
I don't really know how can you reproduce this since there are a limited number of players affected by this bug, including me.

**Expected behavior**
The players price should go up by 1000$ each win the player gets

source: https://ddc.community/index.php?topic=6783.msg67272;topicseen#new

**Comment by ce2kettu** [comment]
Fixed. Rolls and spins are now saved too.
